development:
  adapter: postgresql
  encoding: unicode
  database: trending_development

test:
  adapter: postgresql
  encoding: unicode
  database: trending_test

production:
  adapter: postgresql
  encoding: unicode
  database: trending_production
