cat = Category.create(name: 'popular', full_name: 'Popular')

[ {github_id: 2126244, author: 'twitter', name: 'bootstrap',
      description: "Sleek, intuitive, and powerful front-end framework for faster and easier web development.",
      website_url: "http://twitter.github.io/bootstrap/javascript.html",
      doc_url: "http://twitter.github.io/bootstrap/javascript.html"},
  {github_id: 211666, author: 'joyent', name: 'node',
        description: "evented I/O for v8 javascript",
        website_url: "http://nodejs.org/",
        doc_url: "http://nodejs.org/api/"},
  {github_id: 167174, author: 'jquery', name: 'jquery',
        description: "jQuery JavaScript Library",
        website_url: "http://jquery.com/",
        doc_url: "http://api.jquery.com/"},
  {github_id: 486550, author: 'h5bp', name: 'html5-boilerplate',
        description: "A professional front-end template for building fast, robust, and adaptable web apps or sites.",
        website_url: "http://html5boilerplate.com/",
        doc_url: "https://github.com/h5bp/html5-boilerplate/blob/v4.2.0/doc/TOC.md"},
  {github_id: 3065454, author: 'bartaz', name: 'impress.js',
        description: "It's a presentation framework based on the power of CSS3 transforms and transitions in modern browsers and inspired by the idea behind prezi.com.",
        website_url: "http://bartaz.github.com/impress.js",
        doc_url: "https://github.com/bartaz/impress.js/blob/master/index.html"},
  {github_id: 943149, author: 'mbostock', name: 'd3',
        description: "A JavaScript visualization library for HTML and SVG.",
        website_url: "https://github.com/mbostock/d3",
        doc_url: "https://github.com/mbostock/d3/wiki/API-Reference"},
  {github_id: 952189, author: 'documentcloud', name: 'backbone',
        description: "Give your JS App some Backbone with Models, Views, Collections, and Events",
        website_url: "http://backbonejs.org/",
        doc_url: "http://backbonejs.org/"},
  {github_id: 3470471, author: 'FortAwesome', name: 'Font-Awesome',
        description: "The iconic font designed for use with Twitter Bootstrap",
        website_url: "http://fortawesome.github.io/Font-Awesome/",
        doc_url: "http://fortawesome.github.io/Font-Awesome/#integration"}].each do |library|
  Library.create(library.merge({category_id: cat.id}))
end